Repository ufosc/Echo-Chat, pull requests merged in 2024-02, with the labels that each got.

#117 Commented out Deprecated Actions in Backend
  server/src/_deprecatedActions/createUser.ts
  server/src/_deprecatedActions/deleteMessage.ts
  server/src/_deprecatedActions/deleteUser.ts
  server/src/_deprecatedActions/getMessages.ts
  server/src/_deprecatedActions/getUsers.ts
  server/src/_deprecatedActions/updateUser.ts
Labels: Backend📡

#134 Update backend types
  server/src/actions/createConnectedUser.ts
  server/src/actions/createMessage.ts
  server/src/actions/createUser.ts
  server/src/actions/deleteConnectedUser.ts
  server/src/actions/getConnectedUsers.ts
  server/src/actions/pushMessage.ts
  server/src/actions/updateConnectedUser.ts
  server/src/actions/updateUser.ts
  server/src/index.ts
  server/src/tests/socketio.test.ts
  server/src/types/Message.ts
  server/src/types/User.ts
  server/src/utilities/firebaseInit.ts
Labels: Backend📡, Refactor

#144 Fixed password confirm box.
  client/src/components/Auth/AuthenticationResponse.tsx
  client/src/components/Auth/SignUpScreen.tsx
Labels: Bug, hotfix

#146 Added Rest API tests using axios
  client/src/components/Common/ChatMessage.tsx
  client/src/utils/types.ts
  server/package-lock.json
  server/package.json
  server/src/index.ts
  server/src/tests/express.test.ts
  server/src/tests/socketio.test.ts
Labels: Testing

#147 Fixed some error messages in sign-up screen not displaying properly
  client/src/components/Auth/AuthenticationResponse.tsx
  client/src/components/Auth/SignUpScreen.tsx
Labels: Frontend 🖥, Improvement

#150 Integrate client-server message sending and retrival
  client/src/components/Chat/ChatScreen.tsx
  client/src/components/Common/ChatMessage.tsx
  client/src/components/Common/MessageChannel.tsx
  client/src/contexts/LocationContext.tsx
  client/src/contexts/SettingsContext.tsx
  client/src/contexts/SocketContext.tsx
  client/src/types/Message.ts
  client/src/utils/types.ts
  server/src/index.ts
  server/src/tests/socketio.test.ts
Labels: Feature, Backend📡, Frontend 🖥

#151 Settings screen
  client/src/components/Settings/SettingsItem.tsx
  client/src/components/Settings/SettingsScreen.tsx
Labels: Feature, Frontend 🖥

#141 Added a confirmation window after pressing the signout button and a spinning wheel animation while signing out
  client/src/components/Common/AuthButtons.tsx
Labels: Feature, Frontend 🖥

#180 Firebase Admin Refactor + JWT feature
  .github/workflows/main.yml
  client/src/components/Auth/AuthenticationResponse.tsx
  client/src/components/Auth/LoginScreen.tsx
  client/src/configs/firebaseConfig.ts
  client/src/contexts/LocationContext.tsx
  client/src/contexts/SocketContext.tsx
  client/src/services/store.ts
  server/.gitignore
  server/config_example.md
  server/package-lock.json
  server/package.json
  server/src/actions/createConnectedUser.ts
  server/src/actions/createMessage.ts
  server/src/actions/deleteConnectedUser.ts
  server/src/actions/getConnectedUsers.ts
  server/src/actions/updateConnectedUser.ts
  server/src/index.ts
  server/src/tests/socketio.test.ts
  server/src/utilities/firebaseInit.ts
Labels: Backend📡, Frontend 🖥, Hard
